version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 3000:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./panel:/var/www/html
  nginx:
    image: jguyomard/laravel-nginx:1.13
    ports:
      - 3002:80
  php:

    image: jguyomard/laravel-php:7.2
    volumes:
      - ./api/:/var/www/
      - $HOME/.composer/:$HOME/.composer/
    environment:
      - "DB_HOST=db"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: database
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3003:80"
    links:
       - db
volumes:
  db-data:
